### ISSUE TITLE
Cannot run wp-cli container on /usr/src/wordpress

### ISSUE THREAD

**Issue by gurumark** [TrafeX/docker-wordpress#21] opened 2019-01-26 13:13 UTC
Hi,
I disable wp-cli installation since it is not needed all the time. Running long command using docker exec also gives:
PHP Warning:  levenshtein(): Argument string(s) too long in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/utils.php on line 1186

Instead I try to use the standard way of using wp-li container:

docker run -d \
--name wpcli \
--net xnet \
--volumes-from xgm \
--workdir=/usr/src/wordpress \
--user=82:82 \
wordpress:cli-php7.2 \
sh -c ' \
wp --path=/usr/src/wordpress core install  --url=example.com --title="TEST" --admin_user=admin --admin_password="dfsdsdw" --admin_email=admin@example.com

then I get:
docker logs wpcli 
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.

Am I missing something? I am not familiar with alpine.

Thanks for your help in advance.

**Comment by TrafeX** [comment] 2019-02-03 07:13
Hi @gurumark, that's an interesting issue :wink: 
The problem is that `/usr/src/wordpress` is not a VOLUME in the WordPress container and that's where the WordPress sourcecode can be found. So when you try to use the volumes from the WordPress container (`--volumes-from xgm`), then `/usr/src/wordpress` is not being exported to the wp-cli container.

I tried to make `/usr/src/wordpress` a volume, but that gives some issues with the setup. So I guess the best thing you can do is use the wpcli in the WordPress container and I'll dive some deeper in the volume issue.

**Comment by TrafeX** [comment] 2019-03-15 10:52
I'm closing this issue, please reopen it if I can do anything else for you!

**Closed by TrafeX** 2019-03-15 10:52 UTC
